### PR TITLE
Restructure the git repository

### PR DESCRIPTION
**Pull request by PrasannaGajbhiye**

### CODE REVIEW

**Review by darshanmodh — CHANGES_REQUESTED** [review]
- add .class files in .gitignore

**Comment by darshanmodh** [comment]
If we planning to run proto compiler after pulling code, then no need of .java files generated by protoc

**Comment by PrasannaGajbhiye** [comment]
Haven't decided yet about the time of compiling proto files. So we'll keep it as of now.

**Review by darshanmodh — APPROVED** [review]

**Comment by darshanmodh** [comment]
👍 LGTM

**Pull request merged**
